### ISSUE TITLE
How to process the HowTo100M dataset?

### ISSUE THREAD

**Issue by Unified-Robots** [linjieli222/HERO#13]
Are all the videos segmented in 60s clips? Furthermore, how to process the caption file of HowTo100M?

**Comment by linjieli222** [comment]
Sorry for the delayed reply. I assume you have already processed the caption file as you mentioned in the other thread. Here is an example of a subtitle entry of  a 60s video clip from HowTo100M.
`{"vid_name": "-3BVWtwbV64.0", "sub": [{"start": 0.7989999999999999, "end": 2.335, "text": "Today, twice the hot wax."}, {"start": 2.368, "end": 3.803, "text": "And none of the shirts."}, {"start": 3.836, "end": 5.571, "text": "Let's talk about that."}, {"start": 5.604, "end": 8.441, "text": "( light, enchanted music )"}, {"start": 14.547, "end": 16.449, "text": "Good Mythical Morning."}, {"start": 16.482, "end": 19.218, "text": "We have packed a lot into today's show."}, {"start": 19.251, "end": 21.754, "text": "Yes, we're gonna be trying not to cry"}, {"start": 21.787, "end": 24.724, "text": "with one of stars of the weepiest show on television."}, {"start": 24.757, "end": 28.194, "text": "Plus, our personal puppies will join us for some dog shaming."}, {"start": 28.227, "end": 30.096, "text": "And we're gonna try to figure out"}, {"start": 30.129, "end": 31.831, "text": "exactly what Mike and Alex destroyed."}, {"start": 31.864, "end": 35.635, "text": "But first, let's sniff some scented candles, shall we?"}, {"start": 39.472, "end": 41.641, "text": "All right, for this game, we've asked for some help"}, {"start": 41.674, "end": 43.676, "text": "from Chris Sullivan from \"Guardians of the Galaxy Two\""}, {"start": 43.709, "end": 45.244, "text": "and \"This is Us.\""}, {"start": 45.277, "end": 47.113, "text": "Yeah! Thanks for joining us, Chris!"}, {"start": 47.146, "end": 48.347, "text": "Aw, it's my pleasure."}, {"start": 48.38, "end": 49.749, "text": "- Nice shirt! - Why, thank you."}, {"start": 49.782, "end": 51.517, "text": "Yeah, you decided to wear a shirt today."}, {"start": 51.55, "end": 53.586, "text": "Yes, I came fully clothed."}, {"start": 53.619, "end": 56.489, "text": "And it's very spa-ish, which is very appropriate"}, {"start": 56.522, "end": 58.357, "text": "for what we're gonna be doing."}, {"start": 58.39, "end": 60, "text": "Here the thing, Chris's character on \"This is Us\""}]}`

Hope it helps.
Thanks.

**Comment by Unified-Robots** [comment]
@linjieli222 I have processed a subset of the orginal raw_caption.json of howto100m. And I find a problem: some subtitles are only a part of a sentence. One example is shown blew. How to process these samples?
`{'vid_name': 'RfwZQM-Laf4_00', 'sub': [{'text': 'hi welcome to my new tutorial my name is', 'start': 10.41, 'end': 16.78}, {'text': "Andrea Kruger from degorio today I'm", 'start': 13.63, 'end': 19.21}, {'text': 'going to show you how to create ribbons', 'start': 16.78, 'end': 22.32}, {'text': 'in four different ways', 'start': 19.21, 'end': 22.32}, {'text': 'for this first ribbon you need to create', 'start': 24.02, 'end': 31.56}, {'text': 'a basic shape choose this pen tool and', 'start': 26.98, 'end': 38.71}, {'text': 'create four points so now we need to', 'start': 31.56, 'end': 42.25}, {'text': 'convert this points to smooth click on', 'start': 38.71, 'end': 50.83}, {'text': 'this button and now select this four', 'start': 42.25, 'end': 58.38}, {'text': 'points and convert em also to smooth now', 'start': 50.83, 'end': 60.0}, {'text': 'modify this four points I think', 'start': 58.38, 'end': 60.0}]}`

**Comment by Unified-Robots** [comment]
@linjieli222 After processing the orginal raw_caption.json of howto100m, we find some clips have **too many subtitles** which might cause 'cuda out of memory' error. For example, **90Tr7SSetSA_07** (start from 00) has **282 subtitles**. We download the caption.json from [https://www.rocq.inria.fr/cluster-willow/amiech/howto100m/raw_caption.zip](url). Some subtitles in this zip file are also abnormal such as the captions of 90Tr7SSetSA. Here are some captions in this file: `'['&gt;&gt;HOST:', '&gt;&gt;HOST: ALL', '&gt;&gt;HOST: ALL RIGHT,', '&gt;&gt;HOST: ALL RIGHT, SO', "&gt;&gt;HOST: ALL RIGHT, SO\nWE'VE", "&gt;&gt;HOST: ALL RIGHT, SO\nWE'VE GOT", "&gt;&gt;HOST: ALL RIGHT, SO\nWE'VE GOT SOME", "&gt;&gt;HOST: ALL RIGHT, SO\nWE'VE GOT SOME REALLY", "WE'VE GOT SOME REALLY", "WE'VE GOT SOME REALLY\nGREAT", "WE'VE GOT SOME REALLY\nGREAT THINGS", "WE'VE GOT SOME REALLY\nGREAT THINGS FOR", "WE'VE GOT SOME REALLY\nGREAT THINGS FOR YOUR", 'GREAT THINGS FOR YOUR', 'GREAT THINGS FOR YOUR\nHOME', 'GREAT THINGS FOR YOUR\nHOME THIS', 'GREAT THINGS FOR YOUR\nHOME THIS MORNING', 'GREAT THINGS FOR YOUR\nHOME THIS MORNING TO', 'GREAT THINGS FOR YOUR\nHOME THIS MORNING TO HOM', 'HOME THIS MORNING TO HOM', 'HOME THIS MORNING TO HOM\nHAVE', 'HOME THIS MORNING TO HOM\nHAVE IT', 'HOME THIS MORNING TO HOM\nHAVE IT IT', 'HOME THIS MORNING TO HOM\nHAVE IT IT IT', 'HOME THIS MORNING TO HOM\nHAVE IT IT IT CLEAN,', 'HOME THIS MORNING TO HOM\nHAVE IT IT IT CLEAN, TO', 'HAVE IT IT IT CLEAN, TO', 'HAVE IT IT IT CLEAN, TO\nHELP', 'HAVE IT IT IT CLEAN, TO\nHELP YOU', 'HAVE IT IT IT CLEAN, TO\nHELP YOU FRESHEN', 'HAVE IT IT IT CLEAN, TO\nHELP YOU FRESHEN IT', 'HAVE IT IT IT CLEAN, TO\nHELP YOU FRESHEN IT UP', 'HELP YOU FRESHEN IT UP', "HELP YOU FRESHEN IT UP\nI'M", "HELP YOU FRESHEN IT UP\nI'M GLAD", "HELP YOU FRESHEN IT UP\nI'M GLAD YOU'RE"]`
     How to process such samples? Could you provide us the **orginal** and the **processed** caption.json files? I guess we have used the wrong caption.json file.

**Comment by linjieli222** [comment]
Closed due to inactivity.
