### ISSUE TITLE
One issue about pretrain-tv-init.bin file

### ISSUE THREAD

**Issue by Unified-Robots** [linjieli222/HERO#16]
I'm training the HERO model based on the provided TV dataset. The model needs to pre-load "pretrain-tv-init.bin" to initialize the network. However, I do not know how to obtain this file by ourselves, and I modified the code to ignore this file. But after the pre-training process is finished, the performance is really poor. Is "pretrain-tv-init.bin" essential? If so, how can we obtain this file from scratch?

**Comment by linjieli222** [comment]
https://github.com/linjieli222/HERO/blob/faaf15d6ccc3aa4accd24643d77d75699e9d7fae/scripts/download_tv_pretrain.sh#L37

**Comment by Unified-Robots** [comment]
@linjieli222 

> https://github.com/linjieli222/HERO/blob/faaf15d6ccc3aa4accd24643d77d75699e9d7fae/scripts/download_tv_pretrain.sh#L37

I know you provide this file. But I want to know what should we do to obtain this file totally by ourselves?

**Comment by linjieli222** [comment]
We obtained the RoBERTa pre-trained weights on TVR dataset from the original authors.

**Comment by linjieli222** [comment]
Closed due to inactivity.
