### ISSUE TITLE
Pre-training based on HowTo100M dataset

### ISSUE THREAD

**Issue by Unified-Robots** [linjieli222/HERO#17]
As you have done in your paper, the videos of HowTo100M are segmented into 60s clips. I also processed the caption.json of this dataset to match the segmeted clips. When I pre-trained the model, the error "cuda out of memory" occurs? I guess there are two many subtitles in HowTo100M. How to solve this problem?

**Comment by linjieli222** [comment]
You can try lower the batch size.  For the released pre-trained weights, the experiments are done on 16x 32GB V100 GPUs and we did not encounter "cuda out of memory" with the provided config.

Remember that if you lower the batch size, you will need to either increase the gradient accumulation steps or the total number of training steps. 

Hope it helps. Thanks.

**Comment by Unified-Robots** [comment]
@linjieli222 Thanks for your reply. We will check our code to process the caption.json file of HowTo100M.

**Comment by linjieli222** [comment]
Closed due to inactivity.
