### ISSUE TITLE
The link to didemo_subtitles.db.tar file is invalid

### ISSUE THREAD

**Issue by Unified-Robots** [linjieli222/HERO#20]
When we apply "wget https://convaisharables.blob.core.windows.net/hero/txt_db/didemo_subtitles.db.tar -P $DOWNLOAD/txt_db/", we recieve the message "ERROR 404: The specified blob does not exist". Could you provide a copy of this file?

**Comment by linjieli222** [comment]
Hi,

Thanks for letting us know, we are in the middle of data migration. We will look into it and let you know when it is fixed. In the meantime, we recommend you to try other tasks first. Let us know if other links are broken as well.

Thanks

**Comment by Unified-Robots** [comment]
@linjieli222 Thanks for your reply and your wonderful work. I have tested downstream tasks TVR, TVC and TVQA. They are all okay. Looking forward to your good news.

**Comment by Unified-Robots** [comment]
@linjieli222 Hi, Linjie. For didemo task, we could download all the files except the "didemo_subtitles.db.tar". Could you check whether the link to this file is correct?  It would help us a lot if you could provide a new link to this file.

**Comment by linjieli222** [comment]
Closed due to inactivity.
