### ISSUE TITLE
some questions about inplace 

### ISSUE THREAD

**Issue by y1129800378** [linjieli222/HERO#23]
when i run  train_vcmr.py use my own env(pytorch 1.2),get An error：

**Comment by y1129800378** [comment]
when i run train_vcmr.py use my own env(pytorch 1.2),get An error：
error：

Traceback (most recent call last):
  File "train_vcmr.py", line 403, in <module>
    main(args)
  File "train_vcmr.py", line 232, in main
    scaled_loss.backward()
  File "/data/cdp_algo_ceph_ssd/users/yuyangyin/uniter/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/cdp_algo_ceph_ssd/users/yuyangyin/uniter/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [74, 768]], which is output 0 of SelectBackward, is at version 652; expected version 651 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).


it look like this:
https://discuss.pytorch.org/t/solved-pytorch1-5-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/90256

It is caused by model/model.py L212【transformed_c_v_feats = transformed_c_v_feats + matched_v_feats】

So I am worried there will be problems, and how to fix it?
thanks~

**Comment by Unified-Robots** [comment]
@y1129800378 This may be related with your pytorch version. I used to use pytorch 1.2, and faced with nearly the same problem. I'm now using pytorch 1.7, and do not have this issue for both pre-training and fine-tuning.
