### ISSUE TITLE
Checkpoint for TVQA task

### ISSUE THREAD

**Issue by raksharamesh14** [linjieli222/HERO#27]
Hi, 
Thanks for sharing the code. Where can I download the model after it is finetuned for QA task (i.e., tvqa_default according to the train-tvqa-8gpu.json config )? I'd like to use the finetuned checkpoint for inference on a custom QA dataset directly. Thanks.

**Comment by linjieli222** [comment]
@raksharamesh14 

Thanks for your interests in our project. Sorry about the slow response. 

Here is the pre-trained checkpoint on TVQA: 
https://convaisharables.blob.core.windows.net/hero/finetune/tvqa_default.pt 

Note that this is from a reproduced experiment, so the numbers may be close to the reported results in the paper but not exactly the same.

**Comment by linjieli222** [comment]
Closed due to inactivity.
