### ISSUE TITLE
TVC cannot reproduce results

### ISSUE THREAD

**Issue by Liu0329** [linjieli222/HERO#28]
My cider result is around 35, far from 49.98 in the paper. Anyone has reproduced the results ?

**Comment by linjieli222** [comment]
@Liu0329 

We have run several experiments to reproduce the results after the release. Here is the log of a reproduced experiment:

https://convaisharables.blob.core.windows.net/hero/finetune/tvc_log.txt 

On val split, we were able to get similar performance as what we reported in the paper. Please let me know how I can help you with this.

**Comment by Liu0329** [comment]
That looks good. I use larger batch -size and 4 gpus. I will try your config again.
