### ISSUE TITLE
running on cpu

### ISSUE THREAD

**Issue by Melika-Ayoughi** [linjieli222/HERO#3]
Is it possible to run the pretrained model on cpu? I see the requirement for this project is nvidia (for gpus) but I have a MacBook and it does not have a gpu.

**Comment by linjieli222** [comment]
Sorry for the late reply and thanks for your interests in this project.

Our code is built on GPU, without the support on CPU. However, if you insists on running it on CPU, you can modify the code to disable horovod, apex and set the device to CPU. I believe there are some works to be done to make it happen. But let me know if you encounter any unexpected issues.

Thanks,
Linjie

**Comment by linjieli222** [comment]
Closed due to inactivity.
