### ISSUE TITLE
code for how2r and how2qa 

### ISSUE THREAD

**Issue by tfka** [linjieli222/HERO#35]
Hi,
Thanks for sharing the code. How can I get the script、config、processed data for how2r and how2qa.
I'm looking forward to your replay~

**Comment by linjieli222** [comment]
> Hi,
> 
> Thanks for sharing the code. How can I get the script、config、processed data for how2r and how2qa.
> 
> I'm looking forward to your replay~
> 
> 

Hi,

Please have a check at our [VALUE benchmark](https://value-benchmark.github.io) and it's [starter code](https://github.com/VALUE-Leaderboard/StarterCode).


Thanks.
