### ISSUE TITLE
How long/memory cost does it take to extract all slowest features for howto100m?

### ISSUE THREAD

**Issue by forrestsz** [linjieli222/HERO#39]
How long does it take to extract all features for howto100m? such as slowfast features? and how much memory are used. thanks!

**Comment by linjieli222** [comment]
Hi there,

Thanks for your interests in our HERO project. We used 2 DGX-2 nodes (2 x 16V100 (32GBs)) to extract all features on howto100m. If I remember correctly, the feature extraction costs roughly 2-3 weeks.

**Comment by linjieli222** [comment]
Closed due to inactivity
