### ISSUE TITLE
Feature extractor for custom dataset

### ISSUE THREAD

**Issue by aleSuglia** [linjieli222/HERO#4]
Hello,

Congratulations for your EMNLP paper. Very exciting and impressive results. I was wondering whether you could share the data preprocessing scripts that you used to extract the video features used in your paper.

Thanks,
Alessandro

**Comment by linjieli222** [comment]
Sorry for the late reply and thanks for your interests in this project.

We are actively working on the release of feature extraction code. The estimated release date is mid December. Will let you know when it is out.

Thanks,
Linjie

**Comment by linjieli222** [comment]
Our feature extraction code is now released: [HERO_Video_Feature_Extractor](https://github.com/linjieli222/HERO_Video_Feature_Extractor). The feature pre-processing code (conversion to lmdb) is also updated under here: 1b5d4a4a13ea222fa81ecc623ed58ffeb98b1fa9.

Thanks,
Linjie
