### ISSUE TITLE
Reproducing VCMR results for didemo video only

### ISSUE THREAD

**Issue by hdy007007** [linjieli222/HERO#40]
Hi @linjieli222,
      I have reproduced didemo_video_only, the results results I reproduced are much better than those in the paper.
      The reproduced results are as follow:

672 03/02/2022 21:22:48 - INFO - __main__ -   validation finished in 3 seconds
673 03/02/2022 21:22:51 - INFO - __main__ -   start running  full VCMR evaluationon didemo_video_only test split...
674 03/02/2022 21:22:54 - INFO - __main__ -   metrics_no_nms_VCMR 
675 {   '0.5-r1': 3.590012556504269,
676     '0.5-r10': 16.97737066800603,
677     '0.5-r100': 44.225404319437466,
678     '0.5-r5': 11.299871923656454,
679     '0.7-r1': 2.9875866398794573,
680     '0.7-r10': 14.11497237569061,
681     '0.7-r100': 37.99495228528378,
682     '0.7-r5': 9.289997488699145}

     And the results in paper:

    
![图片](https://user-images.githubusercontent.com/5149252/156591517-9f8a2ab9-60ea-4101-aa52-8f6765e4ad82.png)

I don't find the reason for this result.

**Comment by linjieli222** [comment]
Hi there, 

Thanks for your interests in our HERO project. The release checkpoint is a stronger pre-trained model with longer pre-training steps than what's reported in the paper.
