### ISSUE TITLE
Does the dimension of the input video features have to be 4352?

### ISSUE THREAD

**Issue by onlyonewater** [linjieli222/HERO#42]
Does the dimension of the input video features have to be 4352? I want to use pre-trained I3D to extract my own dataset, which its feature dimension is 1024.

**Comment by linjieli222** [comment]
Sorry about the late response. The feature dimension can be any number that fits to your pre-extracted features. But if you wish to leverage the most out of our pre-trained weights, Slowfast+ResNet101 is preferred. We have explored other features during finetuning in the [VALUE paper](https://arxiv.org/pdf/2106.04632.pdf), results in Table 9 and Section B.1. show that ore-trained weights are transferrable across different vision features.

**Comment by onlyonewater** [comment]
ok, I get it, thanks, I will have a try!
