### ISSUE TITLE
HPS file missing for TVQA task and eval_videoQA.py  fails because of this (how to fix)?

### ISSUE THREAD

**Issue by yrf1** [linjieli222/HERO#43]
Hi, line 42 in _eval_videoQA.py_ reads the hps file: `hps_file = f'{opts.output_dir}/log/hps.json'`
However, no **hps** file is available from running the download script of _scripts/download_tvqa.sh_

Am I missing sth here, or is there a fix that can be posted?

**Comment by yrf1** [comment]
Update: maybe the hps file can be found from _config/train-tvqa-8gpu.json_
Tho documentation would be helpful for ppl coming across in the future:)

**Comment by linjieli222** [comment]
Thanks for your comments. `hps_file` is the configuration stored during training. If you run `train_videoQA.py` first then run `eval_videoQA.py`, you will see such file in the folder where you save the trained model (i.e., the `output_dir` specified for training). `hps_file` can be different from `config/train-tvqa-8gpu.json` if you are not using our default setting for training the video QA model.
