### ISSUE TITLE
The video features used in TVC task

### ISSUE THREAD

**Issue by tuyunbin** [linjieli222/HERO#5]
Hi, Lin jie, How can I repreduce the results in TVC task in your paper?  Can you kindly provide the features you used in this task?
Thanks.

**Comment by linjieli222** [comment]
Sorry about the late reply and thanks for your interests.

The video features for TVC task are the same as the ones used for TVR and TVQA.
@ChenRocks is working on releasing the finetuning code on TVC. Will let you know when it is out.

Thanks,
Linjie

**Comment by tuyunbin** [comment]
Thank you for you reply and I'm looking forward to your released code.

**Comment by linjieli222** [comment]
Hi @tuyunbin,

Code for TVC task has released.  Thanks for your patience.

Best,
Linjie

**Comment by tuyunbin** [comment]
Hi @linjieli222 , thank you very much!

**Comment by tuyunbin** [comment]
Hi,   @linjieli222 ,  can you provide the results on TVC and TVR test-public results without pre-training?
